version: '3'

services:
  postgresdb:
    container_name: postgres_anibook
    image: postgres:12
    environment:
      - POSTGRES_DB=anibook
      - POSTGRES_USER=anibook
      - POSTGRES_PASSWORD=anibook
      - MAX_CONNECTIONS=300
    ports:
      - '5432:5432'
    volumes:
      - ./config/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./config/database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  node:
    build:
      dockerfile: ./config/docker/Dockerfile
      context: .
    image: anibook/node
    container_name: anibook_node
    ports:
      - '4000:4000'
    environment:
      DB_USER_POSTGRES: anibook
      DB_PASS_POSTGRES: anibook
      DB_HOST_POSTGRES: postgres_anibook
      DB_NAME_POSTGRES: anibook
      DB_PORT_POSTGRES: 5432
      TOKEN: anibook
    depends_on:
      - 'postgresdb'
  neo4jdb:
    container_name: neo4j_anibook
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
      - '7473:7473'
    environment:
      - NEO4J_AUTH=neo4j/neo4j12#456
