version: '3'
services:
  db_test:
    container_name: postgres_test
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=anibook_test
      - POSTGRES_USER=anibook_test
      - POSTGRES_PASSWORD=anibook_test
      - MAX_CONNECTIONS=300
    volumes:
      - db-data-test:/var/lib/postgres/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  db_dev:
    container_name: postgres_dev
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=anibook_dev
      - POSTGRES_USER=anibook_dev
      - POSTGRES_PASSWORD=anibook_dev
      - MAX_CONNECTIONS=300
    volumes:
      - db-data-dev:/var/lib/postgres/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment: 
      - MONGO_INITDB_DATABASE=anibook
      - MONGO_INITDB_ROOT_USERNAME=anibook
      - MONGO_INITDB_ROOT_PASSWORD=anibook
volumes: 
  db-data-test:
  db-data-dev:
  mongo_data:
